name: Scrape Exhibitors

on:
  push:
    branches: [ main, master ]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:
    inputs:
      out:
        description: "Output file name (.xlsx or .csv)"
        default: "exhibitors.xlsx"
      args:
        description: "Extra args for go run"
        default: "-dump-html output/list.html -headful=false -timeout 600s"

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      SCRAPER_FILE: s.go              # change if you renamed the scraper
      OUT_FILE: ${{ github.event.inputs.out || 'exhibitors.xlsx' }}
      EXTRA_ARGS: ${{ github.event.inputs.args || '-dump-html output/list.html -headful=false -timeout 600s' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - id: chrome
        name: Install Chrome (for chromedp)
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Ensure go.mod & tidy
        run: |
          [ -f go.mod ] || go mod init github.com/${{ github.repository }}
          go mod tidy

      - name: Run scraper
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}
        run: |
          mkdir -p output
          go run "$SCRAPER_FILE" -out "output/$OUT_FILE" $EXTRA_ARGS

      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: exhibitors-data
          path: output/*
          if-no-files-found: error
          retention-days: 14

      - name: Upload debug artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            output/list.html
            output/*.log
          retention-days: 7
