name: Scrape Exhibitors

on:
  workflow_dispatch:
    inputs:
      out:
        description: "Output file name (.xlsx or .csv)"
        required: false
        default: "exhibitors.xlsx"
  # Optional: run weekly at 03:00 UTC every Monday
  # schedule:
  #   - cron: "0 3 * * 1"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Chrome (for chromedp)
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Ensure go.mod exists & tidy
        run: |
          if [ ! -f go.mod ]; then go mod init github.com/${{ github.repository }}; fi
          go mod tidy

      - name: Run scraper
        run: |
          mkdir -p output
          go run s.go -out "output/${{ github.event.inputs.out || 'exhibitors.xlsx' }}" \
            -headful=false
        env:
          # chromedp will find chrome from PATH provided by setup-chrome
          # but you can force it if needed:
          CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exhibitors-data
          path: output/*
          if-no-files-found: error
          retention-days: 7
