name: Scrape Exhibitors

on:
  push:
    branches: [ main, master ]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:
    inputs:
      out:
        description: "Output file name (.xlsx or .csv)"
        default: "exhibitors.xlsx"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - id: chrome
        name: Install Chrome (for chromedp)
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Ensure go.mod & tidy
        run: |
          [ -f go.mod ] || go mod init github.com/${{ github.repository }}
          go mod tidy

      - name: Run scraper
        run: |
          mkdir -p output
          go run s.go -out "output/${{ github.event.inputs.out || 'exhibitors.xlsx' }}" -headful=false
        env:
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exhibitors-data
          path: output/*
          if-no-files-found: error
          retention-days: 7
